### ISSUE TITLE
Cargo: Handle errors properly in `cargo-marker`

### ISSUE THREAD

**Issue by xFrednet** [rust-marker/marker#169]
`cargo-marker` interacts a lot with other programs or the file system. Therefore, it has to handle numerous `Result<X, Y>` types. Currently, every error is just mapped to a single `ExitStatus` enum, that provides very little information. This is not ideal...

* It might be good to use an existing library for error handling.
* Errors should provide as much information as possible.
* Only the CLI part of `cargo_marker` should "know" what an exit status is.

**Comment by Veetaha** [comment]
I'd like to claim this issue

**Comment by xFrednet** [comment]
You're very welcome to, feel free to add the dependencies you already mentioned previously :)
