### ISSUE TITLE
Make `#[non_exhaustive]` in the api crate optional

### ISSUE THREAD

**Issue by xFrednet** [rust-marker/marker#25]
Almost every enum and struct in the API has the `#[non_exhaustive]` marker to ensure that it can easily be expanded. This is nice for stability, but not ideal for driver implementations. There could also be users who would prefer a failing compilation, rather than adding wildcards to every match statement.

For this reason, I would like to have a feature (which is enabled by default) that can enable the `#[non_exhaustive]` marker.

The implementation will probably be as simple as using:
```rs
#[cfg_attr(feature = "add-non-exhaustive", non_exhaustive)]
```
The feature name is just an example, another name might be better

The feature should also include some documentation, that disabling it (not using default features) might cause compilation failures when the API is updated.

**Comment by DevinR528** [comment]
Would this cause problems if some lints have this feature on and some off and I try to use lints from both? Or is each lint compiled with its own deps and so this would be perfectly fine?

**Comment by xFrednet** [comment]
Ohh, that's a good question. I would hope not, since we only add an attribute, but this could be the case... We should test this before we implement/merge this.

**Comment by xFrednet** [comment]
https://github.com/rust-lang/rust/issues/89554 suggests a new rustc lint that warns if a `match` doesn't cover all variants of a `non_exhaustive` enum. That lint covers exactly the reason why I suggested making the `#[non_exhaustive]` attributes optional.

It's sadly limited to nightly for now, but that'll work for the driver and adapter for now :)
