### ISSUE TITLE
Mega-nit

### ISSUE THREAD

**Issue by smoelius** [rust-marker/marker#254]
I don't know if there is a standard convention, but this doc comment does not end with a period: https://github.com/rust-marker/marker/blob/d150950351ce90f0d12a7f5042d1a5afa3e93f90/marker_adapter/src/loader.rs#L12
Whereas, this one does: https://github.com/rust-marker/marker/blob/d150950351ce90f0d12a7f5042d1a5afa3e93f90/marker_adapter/src/loader.rs#L14

**Comment by xFrednet** [comment]
Yeah, I don't think this is important enough to have a PR, but I'll include it in my next commit. There are probably several places. Reading, updating and adding documentation is on the todo list, but sadly has a low prio rn
