### ISSUE TITLE
Rename `CallExpr::operand` to `CallExpr::func`

### ISSUE THREAD

**Issue by Veetaha** [rust-marker/marker#295]
Operand is the "argument" for the operator, thus having both `operand()` and `args()` looks confusing. The `operator` is what the thing that is invoked, it seems to me like an oversight in terminology.

https://docs.rs/marker_api/latest/marker_api/ast/struct.CallExpr.html#method.operand

**Comment by xFrednet** [comment]
The official docs call the function the `operand`

> A call expression calls a function. The syntax of a call expression is an expression, called the *function operand*, followed by a parenthesized comma-separated list of expression, called the *argument operands*. 
>
> ~https://doc.rust-lang.org/reference/expressions/call-expr.html#call-expressions

Which is why I've chosen it as the official name, but I see the possible confusion. I'm fine with changing it, if this makes the API clearer

**Comment by Veetaha** [comment]
The official docs call the function the `operand`, because they treat `()` as the `operator`, in which case it has two "operands": the function and its arguments list. So both of them are "operands".

I propose to follow the naming that `syn` uses for [call expressions](https://docs.rs/syn/latest/syn/struct.ExprCall.html) meaning `func` and `args`.
