### ISSUE TITLE
[Feat]: Add a method to check if type implements a trait

### ISSUE THREAD

**Issue by Veetaha** [rust-marker/marker#305]
### Summary

I'd like to implement a lint that checks for unnecessary method calls, when the original value already implements the required trait.
For example useless `.into_iter()` calls where the function already accepts `impl IntoIterator`.

**Comment by xFrednet** [comment]
I believe this is a duplicate of https://github.com/rust-marker/marker/issues/141

Either way, definitely something I want to have soon for Marker.

**Comment by xFrednet** [comment]
I'll close this issue, in favor of #141
