### ISSUE TITLE
Make it easier to try out this project

### ISSUE THREAD

**Issue by kangalio** [rust-marker/marker#59]
I had to experiment for quite some time until I got the first lints to actually appear. In the end, this is what I did:
- Move `linter_lints/tests/ui/find_item.rs` to `linter_lints/examples/find_item.rs`
- Run `cargo run --bin cargo-linter -- -l ./linter_lints -- --package linter_lints --example find_item`
  - (Actually, I ran `RUSTC_WORKSPACE_WRAPPER=target/debug/linter_driver_rustc LINTER_LINT_CRATES=target/linter/lints/liblinter_lints.so cargo check --package linter_lints --example find_item` because I want to understand what is happening under the hood; I find the wrapper crates confusing)

Perhaps something like this can be added to the README, to make it easier for new people to check out this work?

**Comment by xFrednet** [comment]
Updating the cargo interface, and critically documenting it, is the next thing on the todo list. This will at least solve part of this. The second part, how to create and test a lint crate will sadly have to wait a bit. Until then, this is a great help! :upside_down_face:

**Comment by xFrednet** [comment]
Also documenting on how to work on this project, is a thing that should be done. Currently, I'm still breaking a lot on a daily basis, but starting on documenting that should also be more on my mind. :)
