### ISSUE TITLE
Diagnostic customization

### ISSUE THREAD

**Issue by Niki4tap** [rust-marker/marker#76]
Rustc has a good API for this that clippy uses: https://doc.rust-lang.org/stable/nightly-rustc/rustc_errors/struct.DiagnosticBuilder.html

Marker should probably have something like this too :)

**Comment by xFrednet** [comment]
Agreed, related to: https://github.com/rust-marker/marker/issues/47

We should be careful, to decide which API we want to provide since we'll require all backends to support that. On the other hand there is currently only rustc and RA which support the same things
